% MIT License
% 
% Copyright (c) 2016 Sotiris Papatheodorou
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.

function out1 = FJnj(a,t,xi,xj,yi,yj)
%FJNJ
%    OUT1 = FJNJ(A,T,XI,XJ,YI,YJ)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    19-May-2016 02:04:57

t2 = yi-yj;
t3 = xi-xj;
t4 = t2.^2;
t5 = 1.0./t3.^2;
t6 = t4.*t5;
t7 = t6+1.0;
t8 = 1.0./sqrt(t7);
t9 = t3.^2;
t10 = t9.*(1.0./4.0);
t11 = t4.*(1.0./4.0);
t12 = a.^2;
t13 = t10+t11-t12;
t14 = sqrt(t13);
t15 = sinh(t);
t16 = cosh(t);
t17 = t8.*t14.*t16;
t18 = 1.0./t3;
t19 = a.*t2.*t8.*t15.*t18;
t20 = t17+t19;
t21 = abs(t20);
t23 = a.*t8.*t15;
t24 = t2.*t8.*t14.*t16.*t18;
t25 = t23-t24;
t22 = abs(t25);
t26 = t21.^2;
t27 = t22.^2;
t28 = t26+t27;
t29 = 1.0./sqrt(t28);
t30 = conj(t14);
t31 = a.*t2.*t8.*t16.*t18;
t33 = t8.*t15.*t30;
t34 = t31+t33;
t35 = t20.*t29.*t34;
t36 = a.*t8.*t16;
t37 = t2.*t8.*t15.*t18.*t30;
t38 = t36-t37;
t39 = t25.*t29.*t38;
t40 = t35+t39;
t46 = t8.*t14.*t15;
t47 = t20.*t29.*t40;
t48 = t31+t46-t47;
t32 = abs(t48);
t42 = t25.*t29.*t40;
t43 = t2.*t8.*t14.*t15.*t18;
t44 = -t36+t42+t43;
t41 = abs(t44);
t45 = 1.0./t7.^(3.0./2.0);
t49 = t32.^2;
t50 = t41.^2;
t51 = t49+t50;
t52 = 1.0./sqrt(t51);
t53 = 1.0./t30;
t54 = xi.*(1.0./2.0);
t55 = t54-xj.*(1.0./2.0);
t56 = 1.0./t3.^3;
t57 = 1.0./t3.^4;
t58 = yi.*2.0;
t62 = yj.*2.0;
t59 = t58-t62;
t60 = yi.*(1.0./2.0);
t61 = t60-yj.*(1.0./2.0);
out1 = [t44.*t52.*(a.*t4.*t16.*t45.*t56+t2.*t5.*t8.*t15.*t30-t2.*t8.*t15.*t18.*t53.*t55.*(1.0./2.0)-t2.*t4.*t15.*t30.*t45.*t57+1.0./2.0)-t48.*t52.*(t8.*t15.*t53.*t55.*(1.0./2.0)-a.*t2.*t5.*t8.*t16+t4.*t15.*t30.*t45.*t56+a.*t2.*t4.*t16.*t45.*t57);-t44.*t52.*(t8.*t15.*t18.*t30+a.*t5.*t16.*t45.*t59.*(1.0./2.0)+t2.*t8.*t15.*t18.*t53.*t61.*(1.0./2.0)-t2.*t15.*t30.*t45.*t56.*t59.*(1.0./2.0))-t48.*t52.*(a.*t8.*t16.*t18+t8.*t15.*t53.*t61.*(1.0./2.0)-t5.*t15.*t30.*t45.*t59.*(1.0./2.0)-a.*t2.*t16.*t45.*t56.*t59.*(1.0./2.0)+1.0./2.0)];
